ass-2/ass-2/Controllers/ComputersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ass_2.Models;

namespace ass_2.Controllers
{
    public class ComputersController : Controller
    {
        // GET: Computers
      

        private ass2Entities001 db = new ass2Entities001();

        // GET: Com
        
        // GET: Com/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            computers com = db.computers.Find(id);
            if (com == null)
            {
                return HttpNotFound();
            }
            return View(com);
        }

        // GET: Com/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Com/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,category,price")] computers com)
        {
            if (ModelState.IsValid)
            {
                db.computers.Add(com);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(com);
        }

        // GET: Com/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            computers com = db.computers.Find(id);
            if (com == null)
            {
                return HttpNotFound();
            }
            return View(com);
        }

        // POST: Com/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,category,price")] computers com)
        {
            if (ModelState.IsValid)
            {
                db.Entry(com).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(com);
        }

        // GET: Com/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            computers com = db.computers.Find(id);
            if (com == null)
            {
                return HttpNotFound();
            }
            return View(com);
        }

        // POST: Com/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            computers com = db.computers.Find(id);
            db.computers.Remove(com);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Index(string sortOrder, string categoryFilter, string searchString)
        {
           

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";
            ViewBag.CategoryFilter = categoryFilter;

            var computers = from c in db.computers
                            select c;
            switch (sortOrder)
            {
                case "name_desc":
                    computers = computers.OrderByDescending(c => c.name);
                    break;
                case "Price":
                    computers = computers.OrderBy(c => c.price);
                    break;
                case "price_desc":
                    computers = computers.OrderByDescending(c => c.price);
                    break;
                default:
                    computers = computers.OrderBy(c => c.name);
                    break;
            }

            if (!String.IsNullOrEmpty(categoryFilter) && categoryFilter != "all")
            {
                computers = computers.Where(c => c.category == categoryFilter);
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                computers = computers.Where(c => c.name.Contains(searchString));
            }
            return View(computers.ToList());
        }
    }
}

ass-2/ass-2/Controllers/DiscountsController.cs
using ass_2.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

public class DiscountsController : Controller
{
    // 创建一个Discount的列表
    private List<Discount> discounts = new List<Discount>
    {
        new Discount { Name = "R9000p", OriginalPrice = 1099, CurrentPrice = 999, ImageUrl = "Content/images/copt1.jpg" },
        new Discount { Name = "R7000P", OriginalPrice = 899, CurrentPrice = 809, ImageUrl = "url2" },
        // 添加更多的Discount对象...
    };

    // GET: Discounts
    public ActionResult Index()
    {
        // 使用创建的Discount列表
        return View(discounts);
    }

    // GET: Discounts/Details/5
    public ActionResult Details(string id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        // 在Discount列表中查找对应的Discount对象
        Discount discount = discounts.FirstOrDefault(d => d.Name == id);
        if (discount == null)
        {
            return HttpNotFound();
        }

        if (id == "Double 11 Special Discount")
        {
            // Add your logic for Double 11 Special Discount here
        }

        return View(discount);
    }
    // GET: Discounts/Edit/5
    public ActionResult Edit()
    {
        
        return View();
    }
    // 其他的方法...

    // 注意：因为你不再使用数据库，所以不需要Dispose方法
}

ass-2/ass-2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("ComputerStore", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="切换导航" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Main", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    
                    <li>@Html.ActionLink("Repository", "Index", "Computers", new { area = "https://localhost:44319/Computers" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Activities", "Index", "Discounts", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p><a href="mailto:983685069@qq.com">983685069@qq.com</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>